services:
  url-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: url-monitor-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      # Optional: Mount a volume for persistent data
      - url-monitor-data:/app/data
    networks:
      - url-monitor-network
    # Resource limits for better performance
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  url-monitor-network:
    driver: bridge

volumes:
  url-monitor-data:
    driver: local
